version: '3'

services:
  web:
    image: php:8.1.3-apache
    volumes:
    #   - ../backend:/var/www/html/
      # - ../frontend:/var/www/html/
      - ../index.html:/var/www/html/
      # - ./config:/var/www/html/backend/
      # - ./.htaccess:/var/www/html/backend/
      # - ./config.js:/var/www/html/frontend/
    # command: apt-get update -y; a2enmod rewrite && /etc/init.d/apache2 restart
    restart: always
    ports:
      - "8080:80"
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: "root"